//
//  Models.swift
//  ProofOfPath
//
//  Every model is a value type, Codable, and stored locally.
//  Nothing here is generated by the app — every field is user-entered.
//

import Foundation

// MARK: - Hard constraint

enum ConstraintCheck: Codable, Hashable {
    /// Option's initial cost must not exceed the value.
    case maximumCost(Double)
    /// Option's initial cost must be at least the value.
    case minimumCost(Double)
    /// Measured value on the linked criterion must be >= value.
    case criterionAtLeast(criterionID: UUID, value: Double)
    /// Measured value on the linked criterion must be <= value.
    case criterionAtMost(criterionID: UUID, value: Double)
    /// A Yes/No criterion must be answered "Yes".
    case criterionMustBeYes(criterionID: UUID)
    /// The user marks each option manually.
    case manual

    var kindTitle: String {
        switch self {
        case .maximumCost: return "Maximum cost"
        case .minimumCost: return "Minimum cost"
        case .criterionAtLeast: return "Criterion at least"
        case .criterionAtMost: return "Criterion at most"
        case .criterionMustBeYes: return "Criterion must be Yes"
        case .manual: return "Checked manually"
        }
    }

    var linkedCriterionID: UUID? {
        switch self {
        case .criterionAtLeast(let id, _), .criterionAtMost(let id, _), .criterionMustBeYes(let id):
            return id
        default:
            return nil
        }
    }

    var isAutomatic: Bool {
        if case .manual = self { return false }
        return true
    }
}

struct HardConstraint: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var title: String = ""
    var details: String = ""
    var check: ConstraintCheck = .manual
    var createdAt: Date = Date()
}

// MARK: - Criterion

struct Criterion: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var name: String = ""
    var details: String = ""
    var importance: CriterionImportance = .niceToHave
    var kind: CriterionKind = .ratingScale
    var measurementMethod: String = ""
    var targetValue: String = ""
    var minimumAcceptableValue: String = ""
    /// Percent of the total weight. All criteria share one 100% budget.
    var weight: Double = 0
    var sortIndex: Int = 0
    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    var displayName: String { name.popIsBlank ? "Untitled criterion" : name }
}

// MARK: - Evaluation

struct Evaluation: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var criterionID: UUID
    /// Free-form measured value as typed by the user ("18 h", "1 250", "Yes").
    var measuredValue: String = ""
    /// Parsed numeric value when the criterion expects one.
    var numericValue: Double?
    /// Answer for Yes/No criteria.
    var boolValue: Bool?
    /// 1...ratingScaleMax.
    var rating: Int?
    var reason: String = ""
    var confidence: ConfidenceLevel = .medium
    var updatedAt: Date = Date()
    var hasBeenEdited: Bool = false

    init(criterionID: UUID) {
        self.criterionID = criterionID
    }

    /// True when the user has actually recorded a judgement.
    var hasJudgement: Bool {
        rating != nil || boolValue != nil
    }

    /// True when a raw measurement has been entered.
    var hasMeasurement: Bool {
        !measuredValue.popIsBlank || numericValue != nil || boolValue != nil
    }

    var hasExplanation: Bool { !reason.popIsBlank }

    var isEmpty: Bool {
        !hasJudgement && !hasMeasurement && reason.popIsBlank
    }
}

// MARK: - Cost model

struct OptionCostModel: Codable, Hashable {
    var recurringCost: Double?
    var recurringPeriod: CostPeriod = .monthly
    var requiredExtras: Double?
    var estimatedMaintenance: Double?
    /// Maintenance is expressed per year to keep the arithmetic honest.
    var potentialSavings: Double?
    var assumptions: String = ""

    var isEmpty: Bool {
        recurringCost == nil && requiredExtras == nil && estimatedMaintenance == nil
            && potentialSavings == nil && assumptions.popIsBlank
    }
}

// MARK: - Option

struct DecisionOption: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var name: String = ""
    var providerOrBrand: String = ""
    var estimatedCost: Double?
    var website: String = ""
    var contactDetails: String = ""
    var availability: String = ""
    var keyDetails: String = ""
    var imageFileName: String?
    var status: OptionStatus = .researching
    var evaluations: [Evaluation] = []
    var cost: OptionCostModel = OptionCostModel()
    var manualConstraintStatus: [String: ManualConstraintStatus] = [:]
    var sortIndex: Int = 0
    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    var displayName: String { name.popIsBlank ? "Untitled option" : name }

    func evaluation(for criterionID: UUID) -> Evaluation? {
        evaluations.first { $0.criterionID == criterionID }
    }

    func manualStatus(for constraintID: UUID) -> ManualConstraintStatus {
        manualConstraintStatus[constraintID.uuidString] ?? .unknown
    }

    var normalizedName: String { name.popNormalizedForCompare }
}

// MARK: - Evidence

struct EvidenceAttachment: Codable, Hashable {
    var fileName: String
    var originalName: String
    var byteSize: Int64
    var isImage: Bool
    var addedAt: Date = Date()
}

struct EvidenceLink: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var optionID: UUID?
    var criterionID: UUID?
    var relation: EvidenceRelation = .context

    var isEmpty: Bool { optionID == nil && criterionID == nil }
}

struct Evidence: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var decisionID: UUID?
    var title: String = ""
    var type: EvidenceType = .website
    var source: String = ""
    var dateCollected: Date = Date()
    var summary: String = ""
    var confidence: ConfidenceLevel = .medium
    var verification: VerificationStatus = .unreviewed
    /// The app never claims to have checked a link automatically.
    var sourceChecked: Bool = false
    var attachment: EvidenceAttachment?
    var links: [EvidenceLink] = []
    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    var displayTitle: String { title.popIsBlank ? "Untitled evidence" : title }

    /// Spec: at least one of Source, Summary or Attachment must be present.
    var hasMinimumContent: Bool {
        !source.popIsBlank || !summary.popIsBlank || attachment != nil
    }

    var hasExternalSource: Bool { !source.popIsBlank }

    func links(optionID: UUID?, criterionID: UUID?) -> [EvidenceLink] {
        links.filter { $0.optionID == optionID && $0.criterionID == criterionID }
    }

    func supports(optionID: UUID, criterionID: UUID) -> Bool {
        links.contains { $0.optionID == optionID && $0.criterionID == criterionID && $0.relation == .supports }
    }

    func contradicts(optionID: UUID, criterionID: UUID) -> Bool {
        links.contains { $0.optionID == optionID && $0.criterionID == criterionID && $0.relation == .contradicts }
    }
}

// MARK: - Claim

struct Claim: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var text: String = ""
    var claimedBy: String = ""
    var optionID: UUID?
    var date: Date = Date()
    var whyItMatters: String = ""
    var verificationDeadline: Date?
    var status: ClaimStatus = .unverified
    var supportingEvidenceIDs: [UUID] = []
    var contradictingEvidenceIDs: [UUID] = []
    var missingProof: String = ""
    var verificationRequested: Bool = false
    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    var displayText: String { text.popIsBlank ? "Untitled claim" : text }
}

// MARK: - Risk

struct Risk: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var title: String = ""
    /// nil means the risk applies to the whole decision.
    var optionID: UUID?
    var likelihood: RiskScale = .medium
    var impact: RiskScale = .medium
    var warningSigns: String = ""
    var mitigationPlan: String = ""
    var fallbackPlan: String = ""
    var reviewDate: Date?
    var state: RiskState = .open
    var acceptWithoutMitigationReason: String = ""
    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    var displayTitle: String { title.popIsBlank ? "Untitled risk" : title }

    var severityScore: Int { likelihood.weight * impact.weight }

    /// Monitor 1–2 · Needs Action 3–6 · Critical only when both scales are High (9),
    /// which is exactly the case that requires a plan or a written acceptance.
    var category: RiskCategory {
        switch severityScore {
        case ...2: return .monitor
        case 3...6: return .needsAction
        default: return .critical
        }
    }

    var isHighHigh: Bool { likelihood == .high && impact == .high }

    var hasMitigation: Bool { !mitigationPlan.popIsBlank }

    /// High/High risks need a plan or an explicit written acceptance.
    var needsAttentionBeforeFinalizing: Bool {
        guard state != .reduced, state != .occurred else { return false }
        guard isHighHigh else { return false }
        return !hasMitigation && acceptWithoutMitigationReason.popIsBlank
    }
}

// MARK: - Scenario

struct Scenario: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var name: String = ""
    var preset: ScenarioPreset = .custom
    var budgetLimit: Double?
    var deadline: Date?
    /// criterionID.uuidString -> weight percent
    var weightOverrides: [String: Double] = [:]
    var excludedOptionIDs: [UUID] = []
    var additionalConstraint: String = ""
    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    var displayName: String { name.popIsBlank ? "Untitled scenario" : name }

    func weight(for criterion: Criterion) -> Double {
        weightOverrides[criterion.id.uuidString] ?? criterion.weight
    }
}

// MARK: - Final decision

struct FinalDecision: Codable, Hashable {
    var selectedOptionID: UUID?
    var whyThisOption: String = ""
    var keyEvidenceIDs: [UUID] = []
    var acceptedTradeOffs: String = ""
    var acceptedRisks: String = ""
    /// 1...5
    var confidence: Int = 3
    var decisionDate: Date = Date()
    var outcomeReviewDate: Date = Calendar.current.date(byAdding: .month, value: 3, to: Date()) ?? Date()
    var isDraft: Bool = true
    var finalizedAt: Date?
    var proceedWithGapsReason: String = ""
    var version: Int = 1
}

// MARK: - Outcome review

struct OutcomeReview: Codable, Hashable {
    var expectedOutcome: String = ""
    var actualOutcome: String = ""
    var satisfaction: SatisfactionLevel?
    var budgetAccuracy: AccuracyLevel?
    var timelineAccuracy: AccuracyLevel?
    var occurredRiskIDs: [UUID] = []
    var unexpectedBenefits: String = ""
    var unexpectedProblems: String = ""
    var wouldChooseAgain: RepeatAnswer?
    var whatWouldYouDoDifferently: String = ""
    var isDraft: Bool = true
    var completedAt: Date?
    var updatedAt: Date = Date()

    var isComplete: Bool { !isDraft && completedAt != nil }

    /// Both required fields per spec.
    var canComplete: Bool { satisfaction != nil && wouldChooseAgain != nil }
}

// MARK: - Activity

struct ActivityEvent: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var date: Date = Date()
    var kind: ActivityKind
    var summary: String
    var detail: String = ""
    var optionID: UUID?
    var criterionID: UUID?

    init(kind: ActivityKind, summary: String, detail: String = "", optionID: UUID? = nil, criterionID: UUID? = nil, date: Date = Date()) {
        self.kind = kind
        self.summary = summary
        self.detail = detail
        self.optionID = optionID
        self.criterionID = criterionID
        self.date = date
    }
}

// MARK: - Accepted unknown & follow-up

struct AcceptedUnknown: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    /// Stable identity of the open question this refers to.
    var questionKey: String
    var kind: OpenQuestionKind
    var label: String
    var reason: String
    var acceptedAt: Date = Date()
}

struct FollowUpTask: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var title: String
    var notes: String = ""
    var dueDate: Date?
    var isDone: Bool = false
    var relatedQuestionKey: String?
    var createdAt: Date = Date()
}

// MARK: - Snapshot

/// Immutable copy taken when a decision is finalized.
struct DecisionSnapshot: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var version: Int
    var createdAt: Date = Date()
    var reason: String = ""
    var label: String = ""

    var criteria: [Criterion]
    var options: [DecisionOption]
    var evidence: [Evidence]
    var claims: [Claim]
    var risks: [Risk]
    var hardConstraints: [HardConstraint]
    var finalDecision: FinalDecision?
    var selectedOptionName: String = ""
    var leaderScore: Double?
}

// MARK: - Decision

struct Decision: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var title: String = ""
    var category: DecisionCategory = .purchase
    var customCategoryName: String = ""
    var desiredOutcome: String = ""
    var whyItMatters: String = ""
    var peopleAffected: String = ""
    var budgetMin: Double?
    var budgetMax: Double?
    var currencyCode: String = "USD"
    var deadline: Date?
    var preferredCompletionDate: Date?
    var owner: String = ""
    var status: DecisionStatus = .active
    var statusBeforeArchive: DecisionStatus?

    var hardConstraints: [HardConstraint] = []
    var criteria: [Criterion] = []
    var options: [DecisionOption] = []
    var claims: [Claim] = []
    var risks: [Risk] = []
    var scenarios: [Scenario] = []
    var activity: [ActivityEvent] = []
    var snapshots: [DecisionSnapshot] = []
    var acceptedUnknowns: [AcceptedUnknown] = []
    var followUpTasks: [FollowUpTask] = []

    var finalDecision: FinalDecision?
    var outcomeReview: OutcomeReview?

    var costHorizon: CostHorizon = .threeYears
    var templateID: String?

    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    // MARK: Derived

    var displayTitle: String { title.popIsBlank ? "Untitled decision" : title }

    var categoryTitle: String {
        category == .custom && !customCategoryName.popIsBlank ? customCategoryName : category.title
    }

    var sortedCriteria: [Criterion] {
        criteria.sorted { lhs, rhs in
            if lhs.sortIndex != rhs.sortIndex { return lhs.sortIndex < rhs.sortIndex }
            return lhs.createdAt < rhs.createdAt
        }
    }

    var sortedOptions: [DecisionOption] {
        options.sorted { lhs, rhs in
            if lhs.sortIndex != rhs.sortIndex { return lhs.sortIndex < rhs.sortIndex }
            return lhs.createdAt < rhs.createdAt
        }
    }

    /// Options that still participate in comparison.
    var comparableOptions: [DecisionOption] {
        sortedOptions.filter { $0.status.isActiveInComparison }
    }

    var totalWeight: Double {
        criteria.reduce(0) { $0 + $1.weight }
    }

    var isWeightBalanced: Bool { abs(totalWeight - 100) < 0.05 }

    var weightRemaining: Double { 100 - totalWeight }

    var mustHaveCriteria: [Criterion] { sortedCriteria.filter { $0.importance == .mustHave } }

    var isFinalized: Bool { status == .finalized }

    var isEditable: Bool { status == .active || status == .draft }

    var selectedOption: DecisionOption? {
        guard let id = finalDecision?.selectedOptionID else { return nil }
        return options.first { $0.id == id }
    }

    var openClaims: [Claim] { claims.filter { $0.status.isOpen } }

    var criticalRisks: [Risk] {
        risks.filter { $0.category == .critical && $0.state != .reduced }
    }

    var outcomeReviewDate: Date? { finalDecision?.outcomeReviewDate }

    var isReviewDue: Bool {
        guard status == .finalized,
              let reviewDate = finalDecision?.outcomeReviewDate,
              finalDecision?.isDraft == false else { return false }
        if outcomeReview?.isComplete == true { return false }
        return reviewDate <= Date()
    }

    var latestVersion: Int {
        max(finalDecision?.version ?? 1, (snapshots.map(\.version).max() ?? 0))
    }

    /// Newest first, with ties broken by the order they were appended, so the
    /// timeline never reshuffles between launches.
    var sortedActivity: [ActivityEvent] {
        activity.enumerated()
            .sorted { lhs, rhs in
                if lhs.element.date != rhs.element.date { return lhs.element.date > rhs.element.date }
                return lhs.offset > rhs.offset
            }
            .map(\.element)
    }

    func activity(forOption optionID: UUID) -> [ActivityEvent] {
        sortedActivity.filter { $0.optionID == optionID }
    }

    func option(id: UUID?) -> DecisionOption? {
        guard let id else { return nil }
        return options.first { $0.id == id }
    }

    func criterion(id: UUID?) -> Criterion? {
        guard let id else { return nil }
        return criteria.first { $0.id == id }
    }

    func risk(id: UUID?) -> Risk? {
        guard let id else { return nil }
        return risks.first { $0.id == id }
    }

    func claim(id: UUID?) -> Claim? {
        guard let id else { return nil }
        return claims.first { $0.id == id }
    }

    func scenario(id: UUID?) -> Scenario? {
        guard let id else { return nil }
        return scenarios.first { $0.id == id }
    }

    func constraint(id: UUID?) -> HardConstraint? {
        guard let id else { return nil }
        return hardConstraints.first { $0.id == id }
    }
}

// MARK: - Settings

struct AppSettings: Codable, Hashable {
    var defaultCurrency: String = "USD"
    var ratingScaleMax: Int = 5
    var remindersEnabled: Bool = false
    var reminderLeadDays: Int = 3
    var hapticsEnabled: Bool = true
    var ownerName: String = ""
    var onboardingCompleted: Bool = false

    static let supportedCurrencies = ["USD", "EUR", "GBP", "PLN", "CZK", "SEK", "NOK", "CAD", "AUD", "CHF", "JPY", "TRY", "AED", "INR", "BRL", "MXN", "ZAR", "KZT", "UAH"]
    static let supportedScales = [5, 10]
}
